# -*- coding: utf-8 -*-
"""Implementasi_Sistem Parkir Mengurutkan Waktu Kendaraan Dengan Metode_Selection Sorti-2515061003pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180fM0Nt03t9d3eAgwUy0XN5WurFWttLD
"""

def selection_sort_parkir(data_parkir):
    n = len(data_parkir)

    for i in range(n):
        min_idx = i

        for j in range(i + 1, n):
            if data_parkir[j]['durasi'] < data_parkir[min_idx]['durasi']:
                min_idx = j

        data_parkir[i], data_parkir[min_idx] = data_parkir[min_idx], data_parkir[i]

    return data_parkir

kendaraan = [
    {"plat": "BE 1234 SM", "durasi": 120},
    {"plat": "B 9999 XYZ", "durasi": 30},
    {"plat": "D 456 ABC", "durasi": 240},
    {"plat": "A 109 PRO", "durasi": 15}
]

print("=== DATA PARKIR SEBELUM DIURUTKAN ===")
for k in kendaraan:
    print(f"Plat: {k['plat']} | Durasi: {k['durasi']} menit")

hasil_urut = selection_sort_parkir(kendaraan)

print("\n=== REKOMENDASI PEMBAYARAN (BIAYA TERKECIL DAHULU) ===")
tarif_per_jam = 3000
for k in hasil_urut:
    biaya = (k['durasi'] / 60) * tarif_per_jam
    print(f"Plat: {k['plat']} | Durasi: {k['durasi']} menit | Estimasi Biaya: Rp{int(biaya)}")